#ifndef IMAGE_VIEW_SYSTEM_H
#define IMAGE_VIEW_SYSTEM_H

#include <stdbool.h>

// Return values for the image viewer interaction
typedef struct {
    int x;       // Image space X (not screen space)
    int y;       // Image space Y
    bool quit;   // Did the user request to quit/back?
} ImageViewResult;

#ifdef ENABLE_FULL_GRAPHICS

/**
 * Initializes the image view system (if needed).
 */
void image_view_init();

/**
 * Displays a raw RGB image file interactively.
 * Blocks until the user quits or clicks.
 * 
 * @param raw_filepath Path to the .raw image file (generated by tools/image_converter.py)
 * @return ImageViewResult containing click coordinates or quit status
 */
ImageViewResult show_image_interactive(const char* raw_filepath);

#else

// Stub functions for when the feature is disabled
static inline void image_view_init() {}
static inline ImageViewResult show_image_interactive(const char* raw_filepath) {
    ImageViewResult r = {0, 0, true};
    return r;
}

#endif // ENABLE_FULL_GRAPHICS

#endif // IMAGE_VIEW_SYSTEM_H
