[package]
name = "lain-day"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
thiserror = "1.0"
crossterm = "0.28"
rodio = "0.22.2"
fastrand = "2.4.1"
image = "0.25.10"

[dev-dependencies]
pretty_assertions = "1.4"
