#ifndef STRING_IDS_H
#define STRING_IDS_H

typedef enum {
    TEXT_INVALID = 0,
    // Navi Scene Text
    TEXT_NAVI_STATE_TITLE,
    TEXT_NAVI_STATE_DESC1,
    TEXT_NAVI_STATE_DESC2,
    TEXT_NAVI_STATE_DESC3,
    TEXT_NAVI_STATE_DESC4,
    // Navi Scene Choices
    TEXT_CHOICE_NAVI_SHUTDOWN,
    TEXT_CHOICE_NAVI_REBOOT,
    TEXT_CHOICE_NAVI_CONNECT,

    // Entry Scene (00_entry)
    TEXT_ENTRY_DESC1,
    TEXT_ENTRY_DESC2,
    TEXT_ENTRY_DESC3,
    TEXT_ENTRY_DESC4,
    TEXT_ENTRY_DESC5,
    TEXT_CHOICE_OPEN_DOOR,
    TEXT_CHOICE_GO_DOWNSTAIRS,
    TEXT_CHOICE_WAIT_ONE_MINUTE,

    // 00a_wait_one_minute_endprologue
    TEXT_WAIT_DESC1,
    TEXT_WAIT_DESC2,
    TEXT_WAIT_DESC3,
    TEXT_WAIT_DESC4,
    TEXT_WAIT_DESC5,
    TEXT_WAIT_QUOTE,
    TEXT_CHOICE_START_CHAPTER_ONE,

    // 01_lain_room
    TEXT_LAIN_ROOM_TITLE, // Although not rendered directly, might be useful for context
    TEXT_LAIN_ROOM_DESC1,
    TEXT_LAIN_ROOM_DESC2,
    TEXT_LAIN_ROOM_DESC3,
    TEXT_LAIN_ROOM_DESC4,
    TEXT_LAIN_ROOM_DESC5,
    TEXT_CHOICE_TALK_TO_FIGURE,
    TEXT_CHOICE_EXAMINE_NAVI,
    TEXT_CHOICE_LEAVE_ROOM,

    // 01b_navi_shutdown
    TEXT_NAVI_SHUTDOWN_TITLE,
    TEXT_NAVI_SHUTDOWN_DESC1,
    TEXT_NAVI_SHUTDOWN_DESC2,
    TEXT_NAVI_SHUTDOWN_DESC3,
    TEXT_NAVI_SHUTDOWN_DESC4,
    TEXT_NAVI_SHUTDOWN_QUOTE,

    // 01c_talk_to_figure_endprologue
    TEXT_TALK_FIGURE_TITLE,
    TEXT_TALK_FIGURE_DESC1,
    TEXT_TALK_FIGURE_YOU_QUOTE1,
    TEXT_TALK_FIGURE_DESC2,
    TEXT_TALK_FIGURE_GHOST_QUOTE1,
    TEXT_TALK_FIGURE_GHOST_QUOTE2,
    TEXT_TALK_FIGURE_YOU_QUOTE2,
    TEXT_TALK_FIGURE_GHOST_QUOTE3,
    TEXT_TALK_FIGURE_YOU_QUOTE3,
    TEXT_TALK_FIGURE_DESC3,

    // 01d_navi_reboot_endprologue
    TEXT_NAVI_REBOOT_TITLE,
    TEXT_NAVI_REBOOT_DESC1,
    TEXT_NAVI_REBOOT_DESC2,
    TEXT_NAVI_REBOOT_YOU_QUOTE1,
    TEXT_NAVI_REBOOT_DESC3,
    TEXT_NAVI_REBOOT_GHOST_QUOTE1,
    TEXT_NAVI_REBOOT_GHOST_QUOTE2,
    TEXT_NAVI_REBOOT_YOU_QUOTE2,
    TEXT_NAVI_REBOOT_GHOST_QUOTE3,
    TEXT_NAVI_REBOOT_YOU_QUOTE3,
    TEXT_NAVI_REBOOT_DESC4,
    TEXT_NAVI_REBOOT_GHOST_QUOTE4,

    // 01e_navi_connect_endprologue
    TEXT_NAVI_CONNECT_TITLE,
    TEXT_NAVI_CONNECT_DESC1,
    TEXT_NAVI_CONNECT_STATUS_CODE,
    TEXT_NAVI_CONNECT_DESC2,
    TEXT_NAVI_CONNECT_GHOST_QUOTE1,
    TEXT_NAVI_CONNECT_YOU_QUOTE1,
    TEXT_NAVI_CONNECT_GHOST_QUOTE2,
    TEXT_NAVI_CONNECT_YOU_QUOTE2,
    TEXT_NAVI_CONNECT_GHOST_QUOTE3,
    TEXT_NAVI_CONNECT_YOU_QUOTE3,
    TEXT_NAVI_CONNECT_GHOST_QUOTE4,
    TEXT_NAVI_CONNECT_DESC3,
    // The choice is start_chapter_one, which already has an ID TEXT_CHOICE_START_CHAPTER_ONE.

    TEXT_COUNT // Always last, gives a count of total strings
} StringID;

#endif // STRING_IDS_H
