#ifndef STRING_IDS_H
#define STRING_IDS_H

typedef enum {
    TEXT_INVALID = 0,
    TEXT_EMPTY_LINE, // Used for intentional empty lines in scene text
    // Navi Scene Text
    TEXT_NAVI_STATE_TITLE,
    TEXT_NAVI_STATE_DESC1,
    TEXT_NAVI_STATE_DESC2,
    TEXT_NAVI_STATE_DESC3,
    TEXT_NAVI_STATE_DESC4,
    // Navi Scene Choices
    TEXT_CHOICE_NAVI_SHUTDOWN,
    TEXT_CHOICE_NAVI_REBOOT,
    TEXT_CHOICE_NAVI_CONNECT,

    // Entry Scene (00_entry)
    TEXT_ENTRY_DESC1,
    TEXT_ENTRY_DESC2,
    TEXT_ENTRY_DESC3,
    TEXT_ENTRY_DESC4,
    TEXT_ENTRY_DESC5,
    TEXT_CHOICE_OPEN_DOOR,
    TEXT_CHOICE_GO_DOWNSTAIRS,
    TEXT_CHOICE_WAIT_ONE_MINUTE,

    // 00a_wait_one_minute_endprologue
    TEXT_WAIT_DESC1,
    TEXT_WAIT_DESC2,
    TEXT_WAIT_DESC3,
    TEXT_WAIT_DESC4,
    TEXT_WAIT_DESC5,
    TEXT_WAIT_QUOTE,
    TEXT_CHOICE_START_CHAPTER_ONE,

    // 01_lain_room
    TEXT_LAIN_ROOM_TITLE, // Although not rendered directly, might be useful for context
    TEXT_LAIN_ROOM_DESC1,
    TEXT_LAIN_ROOM_DESC2,
    TEXT_LAIN_ROOM_DESC3,
    TEXT_LAIN_ROOM_DESC4,
    TEXT_LAIN_ROOM_DESC5,
    TEXT_CHOICE_TALK_TO_FIGURE,
    TEXT_CHOICE_EXAMINE_NAVI,
    TEXT_CHOICE_LEAVE_ROOM,

    // 01b_navi_shutdown
    TEXT_NAVI_SHUTDOWN_TITLE,
    TEXT_NAVI_SHUTDOWN_DESC1,
    TEXT_NAVI_SHUTDOWN_DESC2,
    TEXT_NAVI_SHUTDOWN_DESC3,
    TEXT_NAVI_SHUTDOWN_DESC4,
    TEXT_NAVI_SHUTDOWN_QUOTE,

    // 01c_talk_to_figure_endprologue
    TEXT_TALK_FIGURE_TITLE,
    TEXT_TALK_FIGURE_DESC1,
    TEXT_TALK_FIGURE_YOU_QUOTE1,
    TEXT_TALK_FIGURE_DESC2,
    TEXT_TALK_FIGURE_GHOST_QUOTE1,
    TEXT_TALK_FIGURE_GHOST_QUOTE2,
    TEXT_TALK_FIGURE_YOU_QUOTE2,
    TEXT_TALK_FIGURE_GHOST_QUOTE3,
    TEXT_TALK_FIGURE_YOU_QUOTE3,
    TEXT_TALK_FIGURE_DESC3,

    // 01d_navi_reboot_endprologue
    TEXT_NAVI_REBOOT_TITLE,
    TEXT_NAVI_REBOOT_DESC1,
    TEXT_NAVI_REBOOT_DESC2,
    TEXT_NAVI_REBOOT_YOU_QUOTE1,
    TEXT_NAVI_REBOOT_DESC3,
    TEXT_NAVI_REBOOT_GHOST_QUOTE1,
    TEXT_NAVI_REBOOT_GHOST_QUOTE2,
    TEXT_NAVI_REBOOT_YOU_QUOTE2,
    TEXT_NAVI_REBOOT_GHOST_QUOTE3,
    TEXT_NAVI_REBOOT_YOU_QUOTE3,
    TEXT_NAVI_REBOOT_DESC4,
    TEXT_NAVI_REBOOT_GHOST_QUOTE4,

    // 01e_navi_connect_endprologue
    TEXT_NAVI_CONNECT_TITLE,
    TEXT_NAVI_CONNECT_DESC1,
    TEXT_NAVI_CONNECT_STATUS_CODE,
    TEXT_NAVI_CONNECT_DESC2,
    TEXT_NAVI_CONNECT_GHOST_QUOTE1,
    TEXT_NAVI_CONNECT_YOU_QUOTE1,
    TEXT_NAVI_CONNECT_GHOST_QUOTE2,
    TEXT_NAVI_CONNECT_YOU_QUOTE2,
    TEXT_NAVI_CONNECT_GHOST_QUOTE3,
    TEXT_NAVI_CONNECT_YOU_QUOTE3,
    TEXT_NAVI_CONNECT_GHOST_QUOTE4,
    TEXT_NAVI_CONNECT_DESC3,
    // The choice is start_chapter_one, which already has an ID TEXT_CHOICE_START_CHAPTER_ONE.

    // 02_downstairs.md
    TEXT_DOWNSTAIRS_DESC1,
    TEXT_DOWNSTAIRS_DESC2,
    TEXT_DOWNSTAIRS_DESC3,
    TEXT_DOWNSTAIRS_DESC4,
    TEXT_DOWNSTAIRS_DESC5,
    TEXT_CHOICE_TALK_TO_DAD,
    TEXT_CHOICE_TALK_TO_MOM,
    TEXT_CHOICE_GET_MILK,
    TEXT_CHOICE_RETURN_TO_UPSTAIRS,

    // 02a_talk_to_dad.md
    TEXT_TALK_TO_DAD_DESC1,
    TEXT_TALK_TO_DAD_DAD_QUOTE1,
    TEXT_TALK_TO_DAD_DESC2,
    TEXT_TALK_TO_DAD_DESC3,
    TEXT_CHOICE_DAD_REPLY_NO,
    TEXT_CHOICE_DAD_ASK_UPGRADE,
    TEXT_CHOICE_DAD_ASK_HELP,

    // 02b_dad_reply_no.md
    TEXT_DAD_REPLY_NO_DESC1,
    TEXT_DAD_REPLY_NO_DAD_QUOTE1,
    TEXT_DAD_REPLY_NO_DESC2,
    TEXT_CHOICE_RETURN_TO_LIVING_ROOM_FROM_DAD, // Specific choice, as the generic one might exist.

    // 02c_dad_ask_help.md
    TEXT_DAD_ASK_HELP_DESC1,
    TEXT_DAD_ASK_HELP_DAD_QUOTE1,
    TEXT_DAD_ASK_HELP_DESC2,
    TEXT_DAD_ASK_HELP_DAD_QUOTE2,
    TEXT_DAD_ASK_HELP_DESC3,
    TEXT_CHOICE_END_HELP_RETURN_TO_LIVING_ROOM,

    // 02d_talk_to_mom_normal.md
    TEXT_TALK_TO_MOM_NORMAL_DESC1,
    TEXT_TALK_TO_MOM_NORMAL_MOM_QUOTE1,
    TEXT_TALK_TO_MOM_NORMAL_DESC2,
    TEXT_CHOICE_MOM_REPLY_FINE,
    TEXT_CHOICE_MOM_REPLY_SILENT,

    // 02e_talk_to_mom_vision.md
    TEXT_TALK_TO_MOM_VISION_DESC1,
    TEXT_TALK_TO_MOM_VISION_MOM_QUOTE1,
    TEXT_TALK_TO_MOM_VISION_DESC2,
    TEXT_CHOICE_MOM_DENY_VISION,
    TEXT_CHOICE_MOM_AGREE_DOCTOR,
    TEXT_CHOICE_MOM_REPLY_SILENT_VISION,

    // 02f_mom_reply_fine_endprologue.md
    TEXT_MOM_REPLY_FINE_TITLE,
    TEXT_MOM_REPLY_FINE_DESC1,
    TEXT_MOM_REPLY_FINE_MOM_QUOTE1,
    TEXT_MOM_REPLY_FINE_DESC2,
    TEXT_MOM_REPLY_FINE_DESC3,

    // 02g_mom_reply_silent_endprologue.md
    TEXT_MOM_REPLY_SILENT_TITLE,
    TEXT_MOM_REPLY_SILENT_DESC1,
    TEXT_MOM_REPLY_SILENT_MOM_QUOTE1,
    TEXT_MOM_REPLY_SILENT_DESC2,

    // 02h_mom_deny_vision_endprologue.md
    TEXT_MOM_DENY_VISION_TITLE,
    TEXT_MOM_DENY_VISION_DESC1,
    TEXT_MOM_DENY_VISION_MOM_QUOTE1,
    TEXT_MOM_DENY_VISION_DESC2,
    TEXT_MOM_DENY_VISION_YOU_QUOTE1,
    TEXT_MOM_DENY_VISION_DESC3,
    TEXT_MOM_DENY_VISION_DAD_QUOTE1,
    TEXT_MOM_DENY_VISION_DESC4,

    // 02i_mom_agree_doctor_endprologue.md
    TEXT_MOM_AGREE_DOCTOR_TITLE,
    TEXT_MOM_AGREE_DOCTOR_DESC1,
    TEXT_MOM_AGREE_DOCTOR_DAD_QUOTE1,
    TEXT_MOM_AGREE_DOCTOR_DESC2,
    TEXT_MOM_AGREE_DOCTOR_MOM_QUOTE1,
    TEXT_MOM_AGREE_DOCTOR_DESC3,

    // 02j_get_milk_endprologue.md
    TEXT_GET_MILK_TITLE,
    TEXT_GET_MILK_DESC1,
    TEXT_GET_MILK_DESC2,
    TEXT_GET_MILK_DESC3,
    TEXT_GET_MILK_DESC4,
    TEXT_GET_MILK_PARENT_QUOTE1,
    TEXT_GET_MILK_PARENT_QUOTE2,
    TEXT_GET_MILK_PARENT_QUOTE3,
    TEXT_GET_MILK_PARENT_QUOTE4,
    TEXT_GET_MILK_DESC5,
    TEXT_GET_MILK_DESC6,

    // 03_chapter_one_intro.md
    TEXT_CH1_INTRO_DESC1,
    TEXT_CH1_INTRO_YOU_QUOTE1,
    TEXT_CH1_INTRO_DESC2,
    TEXT_CH1_INTRO_YOU_QUOTE2,
    TEXT_CH1_INTRO_NAVI_QUOTE1,
    TEXT_CH1_INTRO_DESC3,
    TEXT_CH1_INTRO_DESC4,
    TEXT_CHOICE_TALK_TO_SISTER,

    // 04_talk_to_sister conditional scenes
    // Fixed part of the scene
    TEXT_SISTER_FIXED_DESC1, // 你走到门口，姐姐 Mika 看着你。
    TEXT_SISTER_FIXED_DESC2, // 她把手机塞到你手里，不等你反应，就自顾自地开门走了出去。
    TEXT_SISTER_FIXED_DESC3, // Mika: “我先下楼了，你快点。”
    TEXT_SISTER_FIXED_DESC4, // 你现在手里拿着你的手机。这封神秘的邮件，你看还是不看？

    // Cold mood specific
    TEXT_SISTER_COLD_QUOTE1, // Mika: “给。”
    TEXT_SISTER_COLD_QUOTE2, // Mika: “记得带好。今天父母不在，我今晚也出去。晚餐你可以和朋友一起去吃。”

    // Curious mood specific
    TEXT_SISTER_CURIOUS_QUOTE1, // Mika: “哟，今天知道下楼了？昨天一天都把自己关在房间里。”
    TEXT_SISTER_CURIOUS_QUOTE2, // Mika: “给，你的手机。你昨天晚上有封邮件，一个叫‘千砂(Chisa)’的人发来的。”
    TEXT_SISTER_CURIOUS_QUOTE3, // Mika: “我不小心瞄到主题了……说什么‘连接世界’，让你和她一起去个地方……网吧还是游戏厅之类的。”
    TEXT_SISTER_CURIOUS_QUOTE4, // Mika: “父母今天有事，早餐是我准备的，不知道你喜欢什么就拿了面包。”

    // Default mood specific
    TEXT_SISTER_DEFAULT_QUOTE1, // Mika: “你昨天下楼，是因为手机吧？刚刚听你的脚步声，感觉你很急。”
    TEXT_SISTER_DEFAULT_QUOTE2, // Mika: “话说回来，‘千砂(Chisa)’是你男朋友吗？还是普通同学？”
    TEXT_SISTER_DEFAULT_YOU_QUOTE1, // 你： “？”
    TEXT_SISTER_DEFAULT_QUOTE3, // Mika: “看样子你昨天下楼不是为了这个啊……行了，父母今天晚上很晚回来，你可以考虑在外面吃饭。再见。”

    // Shared Choices
    TEXT_CHOICE_READ_EMAIL_FROM_CHISA,
    TEXT_CHOICE_GO_TO_SCHOOL,
    TEXT_CHOICE_DELETE_EMAIL_UNREAD,

    // Mika's Room Locked Scene
    TEXT_MIKA_ROOM_LOCKED_DESC1,
    TEXT_CHOICE_RETURN_TO_UPPER_HALLWAY,

    // Mika's Room Unlocked Scene
    TEXT_MIKA_ROOM_UNLOCKED_DESC1,
    TEXT_MIKA_ROOM_UNLOCKED_MIRA_QUOTE1,
    TEXT_CHOICE_MIKA_ROOM_JUST_LOOKING,
    TEXT_CHOICE_MIKA_ROOM_TALK,

    // Iwakura Upper Hallway Scene
    TEXT_UPPER_HALLWAY_DESC1,
    TEXT_CHOICE_ENTER_LAINS_ROOM,
    TEXT_CHOICE_ENTER_MIKAS_ROOM,
    TEXT_CHOICE_GO_DOWNSTAIRS_FROM_UPPER_HALLWAY, // Renamed to avoid clash with TEXT_CHOICE_GO_DOWNSTAIRS

    // Time Glitch Scene
    SID_TIME_GLITCH_1,
    SID_TIME_GLITCH_2,
    SID_TIME_GLITCH_3,
    SID_TIME_GLITCH_4,
    SID_TIME_GLITCH_CHOICE_1,

    TEXT_COUNT // Always last, gives a count of total strings
} StringID;

#endif // STRING_IDS_H
