#include "../include/string_ids.h"

// For simplicity, directly store the strings here.
// In a real scenario, this could be generated by a build script
// to handle ANSI formatting from simpler input.
const char* g_string_table[TEXT_COUNT] = {
    [TEXT_INVALID] = "ERROR: Invalid Text ID",
    [TEXT_EMPTY_LINE] = "", // Empty string for intentional empty lines

    // Navi Scene Text from 01a_examine_navi.md
    [TEXT_NAVI_STATE_TITLE] = "Navi的状态",
    [TEXT_NAVI_STATE_DESC1] = "你凑近了那台老旧的Navi。屏幕上没有图形界面，只有一个闪烁的光标和一个正在缓慢增长的进度条。",
    [TEXT_NAVI_STATE_DESC2] = "任务描述写着： `DATA ASSIMILATION`",
    [TEXT_NAVI_STATE_DESC3] = "进度： `[==>...................] 3%`",
    [TEXT_NAVI_STATE_DESC4] = "这台机器似乎正在执行某种深刻而底层的任务。在屏幕下方，有几个可用的指令选项。",

    // Navi Scene Choices
    [TEXT_CHOICE_NAVI_SHUTDOWN] = "强制关闭Navi",
    [TEXT_CHOICE_NAVI_REBOOT] = "重启Navi",
    [TEXT_CHOICE_NAVI_CONNECT] = "尝试打开网络链接",

    // Entry Scene (00_entry) Text
    [TEXT_ENTRY_DESC1] = "你站在一个空旷、安静的房间里。",
    [TEXT_ENTRY_DESC2] = "房间里几乎没有东西，只有一扇朴素的门，以及通往楼下的楼梯。",
    [TEXT_ENTRY_DESC3] = "门上用手写体刻着一个词：",
    [TEXT_ENTRY_DESC4] = "lain",
    [TEXT_ENTRY_DESC5] = "但底下的汉字被抹去了",

    // Entry Scene (00_entry) Choices
    [TEXT_CHOICE_OPEN_DOOR] = "打开门",
    [TEXT_CHOICE_GO_DOWNSTAIRS] = "走下楼梯",
    [TEXT_CHOICE_WAIT_ONE_MINUTE] = "保持沉默，等待一分钟",

    // 00a_wait_one_minute_endprologue Text
    [TEXT_WAIT_DESC1] = "你选择什么都不做，只是静静地站在那里。",
    [TEXT_WAIT_DESC2] = "时间一分一秒地过去，房间里只有你自己的呼吸声。就在你开始怀疑这是否是徒劳之时……",
    [TEXT_WAIT_DESC3] = "那扇写着`lain`的门，伴随着一声轻响，自己打开了。",
    [TEXT_WAIT_DESC4] = "一个穿着小熊睡衣的少女从门里走了出来。",
    [TEXT_WAIT_DESC5] = "她平静地看着你，开口问道：",
    [TEXT_WAIT_QUOTE] = "……找我有事吗？",

    // 00a_wait_one_minute_endprologue Choices
    [TEXT_CHOICE_START_CHAPTER_ONE] = "第一章 开始",

    // 01_lain_room Text
    [TEXT_LAIN_ROOM_TITLE] = "lain的房间",
    [TEXT_LAIN_ROOM_DESC1] = "你推开门，向前走了一步，房间内的布局清晰地展现在眼前。",
    [TEXT_LAIN_ROOM_DESC2] = "房间里很暗。一张巨大的书桌占据了角落，靠着两面墙，上面堆满了书籍和设备。在书堆之下，一台老旧的 `Navi` 屏幕亮着幽光。",
    [TEXT_LAIN_ROOM_DESC3] = "房间的中央是一个飘窗。你的右边是一张靠墙的床，床和飘窗之间散落着几个布娃娃。",
    [TEXT_LAIN_ROOM_DESC4] = "而在飘窗上，有一个人影正靠着窗户，静静地坐在窗沿上。",
    [TEXT_LAIN_ROOM_DESC5] = "幽灵少女 盯着月亮 上新月 口里呢喃着 链接", // This is a comment in the original, but I'll add it as a descriptive text here for now

    // 01_lain_room Choices
    [TEXT_CHOICE_TALK_TO_FIGURE] = "和窗边的人说话",
    [TEXT_CHOICE_EXAMINE_NAVI] = "检查那台Navi",
    [TEXT_CHOICE_LEAVE_ROOM] = "默默地离开房间",

    // 01b_navi_shutdown Text
    [TEXT_NAVI_SHUTDOWN_TITLE] = "连接中断",
    [TEXT_NAVI_SHUTDOWN_DESC1] = "你伸出手，按下了Navi的物理关机按钮。",
    [TEXT_NAVI_SHUTDOWN_DESC2] = "屏幕上的进度条和光标瞬间消失，房间唯一的光源熄灭了。世界陷入了彻底的黑暗和寂静。",
    [TEXT_NAVI_SHUTDOWN_DESC3] = "在你的视线余光中，那个坐在窗沿上的人影开始变得不稳定。TA的轮廓像是电视雪花一样闪烁、分解，然后无声无息地消散在了空气里，仿佛从未存在过。",
    [TEXT_NAVI_SHUTDOWN_DESC4] = "黑暗中，你轻声说出了那句话：",
    [TEXT_NAVI_SHUTDOWN_QUOTE] = "……你到现在，还不能原我吗，lain？",

    // 01c_talk_to_figure_endprologue Text
    [TEXT_TALK_FIGURE_TITLE] = "序章结束（结局G：停火）",
    [TEXT_TALK_FIGURE_DESC1] = "你走上前，对着窗边的那个身影开口：",
    [TEXT_TALK_FIGURE_YOU_QUOTE1] = "“你这个幽灵……是想占据我的全部吗？”",
    [TEXT_TALK_FIGURE_DESC2] = "那个身影缓缓地转过头来。TA的脸和你一模一样，但眼神空洞，没有任何情绪。",
    [TEXT_TALK_FIGURE_GHOST_QUOTE1] = "“不知道。我只是被世界选中的载体，而你……是那个进行选择的人。”",
    [TEXT_TALK_FIGURE_GHOST_QUOTE2] = "“我对你的一切毫无兴趣。”",
    [TEXT_TALK_FIGURE_YOU_QUOTE2] = "“但你还是开始入侵我的房间了。”",
    [TEXT_TALK_FIGURE_GHOST_QUOTE3] = "“不是入侵，这一切都是自动。我也没有选择……要不，我们暂时停火好吗？”",
    [TEXT_TALK_FIGURE_YOU_QUOTE3] = "“……希望如此。”",
    [TEXT_TALK_FIGURE_DESC3] = "说完，你转身按下了Navi的电源。屏幕熄灭，房间陷入黑暗。但这一次，你知道，那个“幽灵”并没有消失，只是暂时休眠了。",

    // 01d_navi_reboot_endprologue Text
    [TEXT_NAVI_REBOOT_TITLE] = "序章结束（结局H：重启）",
    [TEXT_NAVI_REBOOT_DESC1] = "你选择了【重启Navi】。屏幕瞬间变黑，然后一行行启动代码飞速滚过。",
    [TEXT_NAVI_REBOOT_DESC2] = "与此同时，窗边的幽灵闪烁了一下，消失了——不，不是消失。TA身上的衣服在一瞬间变了，从白色的连衣裙变成了一套你从未见过的、似乎是某个校服的样式。",
    [TEXT_NAVI_REBOOT_YOU_QUOTE1] = "“所以……你现在是谁？”",
    [TEXT_NAVI_REBOOT_DESC3] = "TA没有立刻回答，而是慢慢向你走来，靠近，然后……轻轻地抱住了你。一个冰冷的、没有实感的拥抱。",
    [TEXT_NAVI_REBOOT_GHOST_QUOTE1] = "幽灵: “我就是你。或者说，是你的一个‘可能’。”",
    [TEXT_NAVI_REBOOT_GHOST_QUOTE2] = "“比如，你曾经想过去美国留学，然后回国当一名医生。”",
    [TEXT_NAVI_REBOOT_YOU_QUOTE2] = "“我没有！”",
    [TEXT_NAVI_REBOOT_GHOST_QUOTE3] = "“所以我说，只是一个‘可能’。那么，你是谁？”",
    [TEXT_NAVI_REBOOT_YOU_QUOTE3] = "“我就是我。”",
    [TEXT_NAVI_REBOOT_DESC4] = "TA松开了拥抱，嘴角似乎有一丝微笑，说出了一句你无法理解的话：",
    [TEXT_NAVI_REBOOT_GHOST_QUOTE4] = "“是吗？我软链接我自己吗？……不，并没有。我们都只是空文件而已。”",

    // 01e_navi_connect_endprologue Text
    [TEXT_NAVI_CONNECT_TITLE] = "序章结束（结局I：403 Forbidden）",
    [TEXT_NAVI_CONNECT_DESC1] = "你选择了【尝试打开网络链接】。屏幕上的进度条消失了，取而代之的是一行冷冰冰的错误代码：",
    [TEXT_NAVI_CONNECT_STATUS_CODE] = "> Status: 403 Forbidden",
    [TEXT_NAVI_CONNECT_DESC2] = "窗边的幽灵开口了，带着一丝嘲弄：",
    [TEXT_NAVI_CONNECT_GHOST_QUOTE1] = "“没用的。你现在只是独自一人。”",
    [TEXT_NAVI_CONNECT_YOU_QUOTE1] = "“你甚至都不是‘人’。”",
    [TEXT_NAVI_CONNECT_GHOST_QUOTE2] = "“不是‘404 Not Found’，就还有希望。你只是被‘拒绝’了……只要你登录那个账号……”",
    [TEXT_NAVI_CONNECT_YOU_QUOTE2] = "“不！你又要怂恿我！我就是不……”",
    [TEXT_NAVI_CONNECT_GHOST_QUOTE3] = "“你会想的。没有人会拒绝被人理解的感觉。”",
    [TEXT_NAVI_CONNECT_YOU_QUOTE3] = "“哪怕是不情愿的吗？”",
    [TEXT_NAVI_CONNECT_GHOST_QUOTE4] = "“是的。”",
    [TEXT_NAVI_CONNECT_DESC3] = "幽灵的话语在寂静的房间里回响。屏幕上的“403 Forbidden”像是一种最终的宣判。",

    // 02_downstairs.md
    [TEXT_DOWNSTAIRS_DESC1] = "你从楼梯上走下来，一股温暖的、生活的气息扑面而来，与楼上的寂静和黑暗截然不同。",
    [TEXT_DOWNSTAIRS_DESC2] = "客厅里，爸爸正坐在沙发上，借着落地灯的光看报纸；姐姐则躺在另一边的沙发上，举着手机煲电话粥。",
    [TEXT_DOWNSTAIRS_DESC3] = "客厅连接着一个开放式厨房，妈妈正在水槽边洗碗，能看到她的背影。冰箱就在她旁边，发出轻微的嗡嗡声。",
    [TEXT_DOWNSTAIRS_DESC4] = "这个家，看起来无比正常。",
    [TEXT_DOWNSTAIRS_DESC5] = "你打算怎么做？",
    [TEXT_CHOICE_TALK_TO_DAD] = "和爸爸说话",
    [TEXT_CHOICE_TALK_TO_MOM] = "走进厨房和妈妈说话",
    [TEXT_CHOICE_GET_MILK] = "去冰箱拿一瓶牛奶",
    [TEXT_CHOICE_RETURN_TO_UPSTAIRS] = "默默地走回楼上",

    // 02a_talk_to_dad.md
    [TEXT_TALK_TO_DAD_DESC1] = "你走到爸爸面前。他从报纸上抬起头，扶了扶眼镜，看着你问道：",
    [TEXT_TALK_TO_DAD_DAD_QUOTE1] = "“lain，这几天熟悉Navi的操作没有？要是有什么困难，可以问我。”",
    [TEXT_TALK_TO_DAD_DESC2] = "他的语气很平常，就像在问你学校的功课一样。",
    [TEXT_TALK_TO_DAD_DESC3] = "你如何回应？",
    [TEXT_CHOICE_DAD_REPLY_NO] = "“还没有。”",
    [TEXT_CHOICE_DAD_ASK_UPGRADE] = "“你能帮我升级Navi吗？”",
    [TEXT_CHOICE_DAD_ASK_HELP] = "“我需要一些帮助。”",

    // 02b_dad_reply_no.md
    [TEXT_DAD_REPLY_NO_DESC1] = "听到你的回答，爸爸点了点头，脸上没有什么特别的表情。他把目光重新投向报纸，随口说道：",
    [TEXT_DAD_REPLY_NO_DAD_QUOTE1] = "“看样子还为时过早……没事，这个Navi是lain的，lain自己可以决定怎么用。”",
    [TEXT_DAD_REPLY_NO_DESC2] = "说完，他便不再作声，似乎完全沉浸在了报纸的世界里。对话自然而然地结束了。",
    [TEXT_CHOICE_RETURN_TO_LIVING_ROOM_FROM_DAD] = "返回客厅",

    // 02c_dad_ask_help.md
    [TEXT_DAD_ASK_HELP_DESC1] = "听到你的请求，爸爸放下了报纸，认真地看向你。",
    [TEXT_DAD_ASK_HELP_DAD_QUOTE1] = "“帮助……吗。也好。”",
    [TEXT_DAD_ASK_HELP_DESC2] = "他沉吟了一下，然后指了指你的方向，仿佛你的眼前就有一块看不见的屏幕。",
    [TEXT_DAD_ASK_HELP_DAD_QUOTE2] = "“世界的基础是连接，而连接的工具就是命令。仔细看好……”",
    [TEXT_DAD_ASK_HELP_DESC3] = "【开发者说明：此处进入游戏的帮助/教程系统。系统将以伪终端的形式，介绍核心的游戏命令，例如 `connect`, `scan`, `read`, `whoami` 等。教程结束后，玩家将返回客厅。】",
    [TEXT_CHOICE_END_HELP_RETURN_TO_LIVING_ROOM] = "结束帮助，返回客厅",

    // 02d_talk_to_mom_normal.md
    [TEXT_TALK_TO_MOM_NORMAL_DESC1] = "你走进厨房，妈妈停下了手中的活，转过身来，脸上带着温柔的微笑。",
    [TEXT_TALK_TO_MOM_NORMAL_MOM_QUOTE1] = "“lain，回来啦。在学校过得怎么样？”",
    [TEXT_TALK_TO_MOM_NORMAL_DESC2] = "她的关心很真切，就像一个普通的母亲。",
    [TEXT_CHOICE_MOM_REPLY_FINE] = "“还好。”",
    [TEXT_CHOICE_MOM_REPLY_SILENT] = "“……” (沉默)",

    // 02e_talk_to_mom_vision.md
    [TEXT_TALK_TO_MOM_VISION_DESC1] = "你走进厨房，妈妈似乎感觉到了什么，她停下手中的活，转过身来，脸上的表情有些担忧。",
    [TEXT_TALK_TO_MOM_VISION_MOM_QUOTE1] = "“lain……你那个幻觉还在吗？要不要……去再见见冬子老师？”",
    [TEXT_TALK_TO_MOM_VISION_DESC2] = "她小心翼翼地措辞，眼神里充满了关切。",
    [TEXT_CHOICE_MOM_DENY_VISION] = "“我没有幻觉。”",
    [TEXT_CHOICE_MOM_AGREE_DOCTOR] = "“也许我该去。”",
    [TEXT_CHOICE_MOM_REPLY_SILENT_VISION] = "“……” (沉默)",

    // 02f_mom_reply_fine_endprologue.md
    [TEXT_MOM_REPLY_FINE_TITLE] = "序章结束（结局A：日常）",
    [TEXT_MOM_REPLY_FINE_DESC1] = "听到你的回答，妈妈点了点头，似乎有些心不在焉。",
    [TEXT_MOM_REPLY_FINE_MOM_QUOTE1] = "“哦……时候不早了，早点休息吧。”",
    [TEXT_MOM_REPLY_FINE_DESC2] = "她说完，便转过身去继续洗碗，不再说话。客厅里只剩下爸爸翻动报纸的沙沙声，和姐姐电话里传来的模糊不清的笑声。",
    [TEXT_MOM_REPLY_FINE_DESC3] = "一切都和往常一样。",

    // 02g_mom_reply_silent_endprologue.md
    [TEXT_MOM_REPLY_SILENT_TITLE] = "序章结束（结局B：沉默）",
    [TEXT_MOM_REPLY_SILENT_DESC1] = "你没有回答，只是静静地站着。妈妈脸上的微笑僵了一下，但很快又恢复了自然。她解下围裙，擦了擦手说道：",
    [TEXT_MOM_REPLY_SILENT_MOM_QUOTE1] = "“时候不早了。去冰箱拿瓶牛奶喝完，早点睡吧。”",
    [TEXT_MOM_REPLY_SILENT_DESC2] = "她没有再追问，也没有再看你，而是开始收拾厨房的台面，似乎已经认定了对话的结束。",

    // 02h_mom_deny_vision_endprologue.md
    [TEXT_MOM_DENY_VISION_TITLE] = "序章结束（结局C：回避）",
    [TEXT_MOM_DENY_VISION_DESC1] = "你试图否认：“我没有……”",
    [TEXT_MOM_DENY_VISION_MOM_QUOTE1] = "“那明天准时登校。”",
    [TEXT_MOM_DENY_VISION_DESC2] = "你还想再说些什么：“我……”",
    [TEXT_MOM_DENY_VISION_YOU_QUOTE1] = "你: “我……”",
    [TEXT_MOM_DENY_VISION_DESC3] = "但客厅另一边的爸爸突然开口，他的声音不大，却不容置疑。他已经放下了报纸。",
    [TEXT_MOM_DENY_VISION_DAD_QUOTE1] = "爸爸: “时间不早了，lain，你先睡吧。这些事情……之后再说。”",
    [TEXT_MOM_DENY_VISION_DESC4] = "家里的空气仿佛凝固了。妈妈不再说话，爸爸也重新拿起了报纸，但没有再翻动。",

    // 02i_mom_agree_doctor_endprologue.md
    [TEXT_MOM_AGREE_DOCTOR_TITLE] = "序章结束（结局D：日记）",
    [TEXT_MOM_AGREE_DOCTOR_DESC1] = "你低声回应：“也许……我应该去。”",
    [TEXT_MOM_AGREE_DOCTOR_DAD_QUOTE1] = "爸爸: “别勉强，lain。你母亲也是在关心你。”",
    [TEXT_MOM_AGREE_DOCTOR_DESC2] = "妈妈则沉默着从厨房的一个抽屉里拿出一个东西，递给你。",
    [TEXT_MOM_AGREE_DOCTOR_MOM_QUOTE1] = "“给。这个是冬子老师给你的……日记本。”",
    [TEXT_MOM_AGREE_DOCTOR_DESC3] = "你接过它——一个崭新的笔记本，还附带一支笔。",

    // 02j_get_milk_endprologue.md
    [TEXT_GET_MILK_TITLE] = "序章结束（结局E：争吵）",
    [TEXT_GET_MILK_DESC1] = "你没有和任何人说话，径直走向厨房，打开冰箱，拿出一瓶牛奶。冰冷的液体滑过喉咙，但你尝不出任何味道。",
    [TEXT_GET_MILK_DESC2] = "你把空瓶子放回桌上，转身默默地走上楼梯。",
    [TEXT_GET_MILK_DESC3] = "在你身后，客厅里传来了父母压抑着的、断断续续的争吵声：",
    [TEXT_GET_MILK_PARENT_QUOTE1] = "“……是你害lain变成这样子……”",
    [TEXT_GET_MILK_PARENT_QUOTE2] = "“……我也是为lain好……”",
    [TEXT_GET_MILK_PARENT_QUOTE3] = "“……还是工作吗？……”",
    [TEXT_GET_MILK_PARENT_QUOTE4] = "“……还是工作吧。”",
    [TEXT_GET_MILK_DESC4] = "争吵声在你走上二楼时渐渐消失。你没有回头。",
    [TEXT_GET_MILK_DESC5] = "你什么也没说，只是默默地看着他们。这个家，似乎有些不对劲。",
    [TEXT_GET_MILK_DESC6] = "但你又说不上来。",

    // 03_chapter_one_intro.md
    [TEXT_CH1_INTRO_DESC1] = "刺耳的闹钟声将你从混沌的睡眠中拽醒。",
    [TEXT_CH1_INTRO_YOU_QUOTE1] = "“……闹钟？”",
    [TEXT_CH1_INTRO_DESC2] = "你喃喃自语，伸手在床头柜上摸索着。",
    [TEXT_CH1_INTRO_YOU_QUOTE2] = "“我的手机呢？”",
    [TEXT_CH1_INTRO_NAVI_QUOTE1] = "【你昨天把手机借给姐姐了。】",
    [TEXT_CH1_INTRO_DESC3] = "你顾不上太多，慌乱地冲下楼。餐桌上放着牛奶和一袋面包，你抓起它们，算是解决了早餐。你看着手中的面包，心里闪过一个念头：“看样子，他们今晚又不在家了。”",
    [TEXT_CH1_INTRO_DESC4] = "正当你准备出门时，你看到姐姐正站在门口，似乎在等你。",
    [TEXT_CHOICE_TALK_TO_SISTER] = "和姐姐说话",

    // 04_talk_to_sister conditional scenes
    // Fixed part of the scene
    [TEXT_SISTER_FIXED_DESC1] = "你走到门口，姐姐 Mika 看着你。",
    [TEXT_SISTER_FIXED_DESC2] = "她把手机塞到你手里，不等你反应，就自顾自地开门走了出去。",
    [TEXT_SISTER_FIXED_DESC3] = "“我先下楼了，你快点。”",
    [TEXT_SISTER_FIXED_DESC4] = "你现在手里拿着你的手机。这封神秘的邮件，你看还是不看？",

    // Cold mood specific
    [TEXT_SISTER_COLD_QUOTE1] = "“给。”",
    [TEXT_SISTER_COLD_QUOTE2] = "“记得带好。今天父母不在，我今晚也出去。晚餐你可以和朋友一起去吃。”",

    // Curious mood specific
    [TEXT_SISTER_CURIOUS_QUOTE1] = "“哟，今天知道下楼了？昨天一天都把自己关在房间里。”",
    [TEXT_SISTER_CURIOUS_QUOTE2] = "“给，你的手机。你昨天晚上有封邮件，一个叫‘千砂(Chisa)’的人发来的。”",
    [TEXT_SISTER_CURIOUS_QUOTE3] = "“我不小心瞄到主题了……说什么‘连接世界’，让你和她一起去个地方……网吧还是游戏厅之类的。”",
    [TEXT_SISTER_CURIOUS_QUOTE4] = "“父母今天有事，早餐是我准备的，不知道你喜欢什么就拿了面包。”",

    // Default mood specific
    [TEXT_SISTER_DEFAULT_QUOTE1] = "“你昨天下楼，是因为手机吧？刚刚听你的脚步声，感觉你很急。”",
    [TEXT_SISTER_DEFAULT_QUOTE2] = "“话说回来，‘千砂(Chisa)’是你男朋友吗？还是普通同学？”",
    [TEXT_SISTER_DEFAULT_YOU_QUOTE1] = "“？”",
    [TEXT_SISTER_DEFAULT_QUOTE3] = "“看样子你昨天下楼不是为了这个啊……行了，父母今天晚上很晚回来，你可以考虑在外面吃饭。再见。”",

    // Shared Choices
    [TEXT_CHOICE_READ_EMAIL_FROM_CHISA] = "查看那封邮件",
    [TEXT_CHOICE_GO_TO_SCHOOL] = "无视邮件，直接去学校",
    [TEXT_CHOICE_DELETE_EMAIL_UNREAD] = "不看，直接删除邮件",

    // Mika's Room Locked Scene
    [TEXT_MIKA_ROOM_LOCKED_DESC1] = "姐姐的房间门紧闭着。你试着转动门把手，但它纹丝不动，显然是从里面锁住了。",
    [TEXT_CHOICE_RETURN_TO_UPPER_HALLWAY] = "转身回到上层走廊",

    // Mika's Room Unlocked Scene
    [TEXT_MIKA_ROOM_UNLOCKED_DESC1] = "你打开了姐姐美香的房门。房间里很整洁，与你自己的房间完全不同。美香正坐在书桌前，回头看了你一眼。",
    [TEXT_MIKA_ROOM_UNLOCKED_MIRA_QUOTE1] = "“什么事？”",
    [TEXT_MIKA_ROOM_UNLOCKED_EMPTY_DESC1] = "你打开了姐姐美香的房门。房间很整洁，但美香不在。",
    [TEXT_CHOICE_MIKA_ROOM_JUST_LOOKING] = "没什么，只是看看。",
    [TEXT_CHOICE_MIKA_ROOM_TALK] = "想和美香聊聊。",
    // Iwakura Upper Hallway Scene
    [TEXT_UPPER_HALLWAY_DESC1] = "连接着房子二楼的房间。",
    [TEXT_CHOICE_ENTER_LAINS_ROOM] = "进入Lain的房间",
    [TEXT_CHOICE_ENTER_MIKAS_ROOM] = "进入美香的房间",
    [TEXT_CHOICE_GO_DOWNSTAIRS_FROM_UPPER_HALLWAY] = "走下楼梯",

    // Time Glitch Scene
    [SID_TIME_GLITCH_1] = "你的NAVI屏幕閃爍著無法辨認的亂碼。時間顯示變成了刺眼的 `[##:##]`。",
    [SID_TIME_GLITCH_2] = "數據流在你眼前扭曲、崩潰。一瞬間，你彷彿看到了无数个自己，在不同的时间线上重复着相同的动作。",
    [SID_TIME_GLITCH_3] = "記憶正在失去同步...",
    [SID_TIME_GLITCH_4] = "存档数据似乎已损坏。时间被重置了。",
    [SID_TIME_GLITCH_CHOICE_1] = "...继续...",

    // Examine Fridge Scene
    [TEXT_EXAMINE_FRIDGE_DESC1] = "你打开冰箱。里面有4盒未开封的1L牛奶，一些面包和罐头等食物。",
    [TEXT_CHOICE_TAKE_MILK] = "拿一盒牛奶",
    [TEXT_CHOICE_CLOSE_FRIDGE] = "关上冰箱门",
};

const char* get_string_by_id(StringID id) {
    if (id > 0 && id < TEXT_COUNT) {
        return g_string_table[id];
    }
    return g_string_table[TEXT_INVALID];
}