#include "../include/string_ids.h"

// For simplicity, directly store the strings here.
// In a real scenario, this could be generated by a build script
// to handle ANSI formatting from simpler input.
const char* g_string_table[TEXT_COUNT] = {
    [TEXT_INVALID] = "ERROR: Invalid Text ID",

    // Navi Scene Text from 01a_examine_navi.md
    [TEXT_NAVI_STATE_TITLE] = "Navi的状态",
    [TEXT_NAVI_STATE_DESC1] = "你凑近了那台老旧的Navi。屏幕上没有图形界面，只有一个闪烁的光标和一个正在缓慢增长的进度条。",
    [TEXT_NAVI_STATE_DESC2] = "任务描述写着： `DATA ASSIMILATION`",
    [TEXT_NAVI_STATE_DESC3] = "进度： `[==>...................] 3%`",
    [TEXT_NAVI_STATE_DESC4] = "这台机器似乎正在执行某种深刻而底层的任务。在屏幕下方，有几个可用的指令选项。",

    // Navi Scene Choices
    [TEXT_CHOICE_NAVI_SHUTDOWN] = "强制关闭Navi",
    [TEXT_CHOICE_NAVI_REBOOT] = "重启Navi",
    [TEXT_CHOICE_NAVI_CONNECT] = "尝试打开网络链接",
};

const char* get_string_by_id(StringID id) {
    if (id > 0 && id < TEXT_COUNT) {
        return g_string_table[id];
    }
    return g_string_table[TEXT_INVALID];
}