# cmake/generate_json_header.cmake
# 这是一个CMake脚本，用于从JSON文件生成一个C头文件

file(READ ${INPUT_FILE} JSON_CONTENT)

# 对JSON内容进行C字符串转义
string(REPLACE "\\" "\\\\" JSON_CONTENT "${JSON_CONTENT}") # 转义反斜杠
string(REPLACE "\"" "\\\"" JSON_CONTENT "${JSON_CONTENT}") # 转义双引号
string(REPLACE "\n" "\\n\"\n\"" JSON_CONTENT "${JSON_CONTENT}") # 处理换行符，并拼接字符串

set(HEADER_CONTENT "
#ifndef GENERATED_CHARACTER_DATA_H
#define GENERATED_CHARACTER_DATA_H

// Auto-generated from ${INPUT_FILE} by CMake
// DO NOT EDIT THIS FILE MANUALLY!

static const char* CHARACTER_JSON_DATA =
\"${JSON_CONTENT}\";

#endif // GENERATED_CHARACTER_DATA_H
")

file(WRITE ${OUTPUT_FILE} "${HEADER_CONTENT}")

