# cmake/generate_json_header.cmake

file(READ ${INPUT_FILE} JSON_CONTENT)

# C-escape the JSON content
string(REPLACE "\\" "\\\\" JSON_CONTENT "${JSON_CONTENT}")
string(REPLACE "\"" "\\\"" JSON_CONTENT "${JSON_CONTENT}")
string(REPLACE "\n" "\\n" JSON_CONTENT "${JSON_CONTENT}")

# Default variable name to CHARACTER_JSON_DATA if not provided
if(NOT DEFINED JSON_VAR_NAME)
  set(JSON_VAR_NAME "CHARACTER_JSON_DATA")
endif()

# Generate a header guard from the variable name
string(TOUPPER ${JSON_VAR_NAME} HEADER_GUARD)
set(HEADER_GUARD "GENERATED_${HEADER_GUARD}_H")

set(HEADER_CONTENT "
#ifndef ${HEADER_GUARD}
#define ${HEADER_GUARD}

// Auto-generated from ${INPUT_FILE} by CMake
// DO NOT EDIT THIS FILE MANUALLY!

static const char* ${JSON_VAR_NAME} =
\"${JSON_CONTENT}\";

#endif // ${HEADER_GUARD}
")

file(WRITE ${OUTPUT_FILE} "${HEADER_CONTENT}")
